# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: testRelease
  # vmImage: 'ubuntu-latest'

steps:
- bash: |
   # Write your commands here
   
   echo 'Hello world'
   uptime
   whoami
   pwd
   echo $PATH
   date
   ls -talr
   #git clone ssh://git@git.nibejpi.com:7999/cloudteam/jpi-cloud-devicemanagement.git
   ls -tarl
   ls jpi-cloud-devicemanagement
   touch hello
   echo "ravi" >> hello
  displayName: 'Bash Script'
  enabled: false
      
