# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: gettingRepository
  jobs:
    - job: Getting_script_repository
      pool: testRelease
      steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              
              Write-Host "Hello World"
              cd C:\Scripts\newDir


 


# steps:

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your PowerShell commands here.
      
#       Write-Host "Hello World"
#       New-Item -ItemType directory -Path C:\Scripts\newDir
      
